import { Tag } from './app/shared/models/Tag';
import {Food} from './app/shared/models/food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: true,
    stars: 4.5,
    imageUrl: 'assets/PepperoniPizza.png',
    tags: ['FastFood', 'Pizza', 'Ebéd'],
  },
  {
    id:'2',
    name: 'Fasírt',
    price: 20,
    cookTime: '20-30',
    favorite: false,
    stars: 4.7,
    imageUrl: 'assets/Fasirt.png',
    tags: ['SlowFood', 'Ebéd'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: true,
    stars: 3.5,
    imageUrl: 'assets/Hamburger.png',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Sültkrumpli',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    stars: 3.3,
    imageUrl: 'assets/Sultkrumpli.png',
    tags: ['FastFood', 'Sült'],
  },
  {
    id:'5',
    name: 'Húsleves',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    stars: 3.0,
    imageUrl: 'assets/Husleves.png',
    tags: ['SlowFood', 'Leves'],
  },
  {
    id:'6',
    name: 'Hawaii Pizza',
    price: 9,
    cookTime: '20-30',
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/HawaiiPizza.png',
    tags: ['FastFood', 'Pizza', 'Ebéd'],
  },
  {
    id:'7',
    name: 'Rantott hús',
    price: 15,
    cookTime: '30-40',
    favorite: true,
    stars: 4.5,
    imageUrl: 'assets/Rantotthus.png',
    tags: ['SlowFood', 'Sült', 'Ebéd'],
  },
  {
    id:'8',
    name: 'Gyümölcsleves',
    price: 10,
    cookTime: '40-50',
    favorite: false,
    stars: 3.5,
    imageUrl: 'assets/Gyumolcsleves.png',
    tags: ['SlowFood', 'Leves'],
  },
  {
    id:'9',
    name: 'Spagetti',
    price: 9,
    cookTime: '20-30',
    favorite: true,
    stars: 5.0,
    imageUrl: 'assets/Spagetti.png',
    tags: ['SlowFood', 'Ebéd'],
  },
  {
    id:'10',
    name: 'Hotdog',
    price: 4,
    cookTime: '10-20',
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/Hotdog.png',
    tags: ['FastFood'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'Összes', count: 10 },
  { name: 'FastFood', count: 5 },
  { name: 'Pizza', count: 2 },
  { name: 'Ebéd', count: 5 },
  { name: 'SlowFood', count: 5 },
  { name: 'Hamburger', count: 1 },
  { name: 'Sült', count: 2 },
  { name: 'Leves', count: 2 },
]
